"""Initial migration

Revision ID: b3db3d1f1a43
Revises: 
Create Date: 2024-07-17 23:17:14.333901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3db3d1f1a43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mariposa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('especie', sa.String(length=80), nullable=False),
    sa.Column('familia', sa.String(length=80), nullable=False),
    sa.Column('nombreCientifico', sa.String(length=80), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=False),
    sa.Column('peligroExtincion', sa.Boolean(), nullable=True),
    sa.Column('migratoria', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mariposa')
    # ### end Alembic commands ###
